### ISSUE TITLE
telegram notifier panic issue

### ISSUE THREAD

**Issue by c9s** [c9s/bbgo#1015]
```
bbgo[56058]: panic: runtime error: invalid memory address or nil pointer dereference
bbgo[56058]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xace224]
bbgo[56058]: goroutine 223 [running]:
bbgo[56058]: github.com/c9s/bbgo/pkg/types.(*ZeroAssetError).Error(0x1484840?)
bbgo[56058]:         <autogenerated>:1 +0x24
bbgo[56058]: github.com/c9s/bbgo/pkg/notifier/telegramnotifier.(*LogHook).Fire(0xc00042e328, 0xc0006300e0)
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/notifier/telegramnotifier/logrus_look.go:39 +0x150
bbgo[56058]: github.com/sirupsen/logrus.LevelHooks.Fire(0xc000add328?, 0xadd2f8?, 0x7ffb00000001?)
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/hooks.go:28 +0x82
bbgo[56058]: github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0006300e0)
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:272 +0x1dc
bbgo[56058]: github.com/sirupsen/logrus.(*Entry).log(0xc000630070, 0x2, {0xc0005203a0, 0x1d})
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:241 +0x34f
bbgo[56058]: github.com/sirupsen/logrus.(*Entry).Log(0xc000630070, 0x2, {0xc000add5c8?, 0x0?, 0x0?})
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
bbgo[56058]: github.com/sirupsen/logrus.(*Entry).Logf(0xc000630070, 0x2, {0x168927a?, 0x5?}, {0x0?, 0x1c92bdda40?, 0xc00042cdf0?})
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0x85
bbgo[56058]: github.com/sirupsen/logrus.(*Entry).Errorf(...)
bbgo[56058]:         /Users/c9s/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:367
bbgo[56058]: github.com/c9s/bbgo/pkg/strategy/pivotshort.(*FailedBreakHigh).Bind.func5({0x0, {0x1661cc8, 0x7}, {0xc001453527, 0x7}, {0x0, 0xedb141cb8, 0x2642000}, {0x3b8b87c0, 0xedb141cf3, ...}, ...})
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/strategy/pivotshort/failedbreakhigh.go:293 +0x1019
bbgo[56058]: github.com/c9s/bbgo/pkg/types.KLineWith.func1({0x0, {0x1661cc8, 0x7}, {0xc001453527, 0x7}, {0x0, 0xedb141cb8, 0x2642000}, {0x3b8b87c0, 0xedb141cf3, ...}, ...})
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/kline.go:652 +0x102
bbgo[56058]: github.com/c9s/bbgo/pkg/types.(*StandardStream).EmitKLineClosed(...)
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/standardstream_callbacks.go:83
bbgo[56058]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).handleKLineEvent(0xc000080c00, 0xc0000efc30)
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream.go:225 +0x238
bbgo[56058]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).EmitKLineEvent(...)
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream_callbacks.go:23
bbgo[56058]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).dispatchEvent(0x7ffbaf1dea20?, {0x138d8c0?, 0xc0000efc30?})
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream.go:346 +0x64c
bbgo[56058]: github.com/c9s/bbgo/pkg/types.(*StandardStream).Read(0xc000080c30, {0x18ca408, 0xc000433540}, 0xc000b56c60, 0x0?)
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/stream.go:248 +0x30e
bbgo[56058]: created by github.com/c9s/bbgo/pkg/types.(*StandardStream).DialAndConnect
bbgo[56058]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/stream.go:348 +0x17b
```

**Comment by zenixls2** [comment]
close the issue?

**Comment by c9s** [comment]
fixed
