### ISSUE TITLE
ewma panic

### ISSUE THREAD

**Issue by c9s** [c9s/bbgo#420]
```
Jan 07 12:20:00 localhost bbgo[820512]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 07 12:20:00 localhost bbgo[820512]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe5de1e]
Jan 07 12:20:00 localhost bbgo[820512]: goroutine 128 [running]:
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/indicator.(*EWMA).Last(...)
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/indicator/ewma.go:40
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/strategy/support.(*Strategy).Run.func1({0x0, {0x12173b6, 0x7}, {0xc0004b4e40, 0x7}, {0x0, 0xed969b544, 0x1ca95a0}, {0x3b8b87c0, 0xed969b66f, ...}, ...})
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/strategy/support/strategy.go:368 +0x77e
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/types.(*StandardStream).EmitKLineClosed(0x90, {0x0, {0x12173b6, 0x7}, {0xc0004b4e40, 0x7}, {0x0, 0xed969b544, 0x1ca95a0}, {0x3b8b87c0, ...}, ...})
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/standardstream_callbacks.go:83 +0x7a
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).handleKLineEvent(0xc0001f7500, 0xc000554210)
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream.go:210 +0xc5
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).EmitKLineEvent(0x0, 0x44ff49)
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream_callbacks.go:23 +0x46
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/exchange/binance.(*Stream).dispatchEvent(0x10, {0x1004e20, 0xc000554210})
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/exchange/binance/stream.go:329 +0xc5
Jan 07 12:20:00 localhost bbgo[820512]: github.com/c9s/bbgo/pkg/types.(*StandardStream).Read(0xc0001f7530, {0x13cf490, 0xc000079300}, 0xc0009f6160, 0x0)
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/stream.go:224 +0x2e7
Jan 07 12:20:00 localhost bbgo[820512]: created by github.com/c9s/bbgo/pkg/types.(*StandardStream).DialAndConnect
Jan 07 12:20:00 localhost bbgo[820512]:         /Users/c9s/src/github.com/c9s/bbgo/pkg/types/stream.go:321 +0x105
```

**Comment by c9s** [comment]
fixed.
